### ISSUE TITLE
Add Gold Sponsor: Code Climate

### ISSUE THREAD

**Issue by abelmartin** [goruco/goruco2018#14]
⚠️ Wait for the final word from @rosscooperman before doing this ⚠️ 

Code Climate was a sponsor in 2016.  You can start by uncommenting their section:

https://github.com/goruco/goruco2018/blob/gh-pages/_data/sponsors.yml#L1-L5

...which will...rehydrate...their 2016 block, image, and modal.

**Comment by rosscooperman** [comment]
They have been invoiced. I asked Bryan to tell me who to talk to about getting a logo/blurb. They rebranded this year so they prolly have some new stuff.

~Ross

Sent via Superhuman ( https://sprh.mn/?vip=cooperman@gmail.com )

**Comment by abelmartin** [comment]
Going to use their image from 2016 with the following blurb copy:

---

Code Climate is automated code review for software development teams. Our open and extensible platform analyzes every commit for complexity, duplication, security, style, test coverage, and more – so you can fix issues sooner and ship better code faster. 

Code Climate engineers build software that runs static analysis at scale, analyzing billions lines of code daily across over tens of thousands repositories. We use and improve the software we build every day to deliver analysis wherever you work – on premise, on the command line, in your editor, and in the cloud.

**Comment by abelmartin** [comment]
Done.  Needs #38
