### ISSUE TITLE
Add Scholarship Sponsor: Ruth Ann Harnisch

### ISSUE THREAD

**Issue by jcn** [goruco/goruco2018#27]
No logo
Text: Ruth Ann Harnisch
Link: http://thehf.org/ruth_ann_writes/

**Comment by abelmartin** [comment]
Using 
![the-harnisch-foundation](https://user-images.githubusercontent.com/29429/40899073-05df7c3c-6793-11e8-8ada-9649d11e53a6.png)

* the word "Foundation" is in white so it doesn't appear here, but it will on the site

**Comment by jcn** [comment]
Actually we should just use her name - the scholarship is _not_ coming from the Harnish Foundation, it's coming from Ruth Ann directly.

**Comment by abelmartin** [comment]
Good to know, I won't use the foundation, just her name.  Thanks

**Comment by abelmartin** [comment]
Done
