### ISSUE TITLE
Add Bronze Sponsor: SevenFifty

### ISSUE THREAD

**Issue by rosscooperman** [goruco/goruco2018#28]
[SevenFifty_Logo_Medium_OUTLINED (1).ai.zip](https://github.com/goruco/goruco2018/files/2052271/SevenFifty_Logo_Medium_OUTLINED.1.ai.zip)

**Comment by abelmartin** [comment]
Logo done.  Need blurb

**Comment by abelmartin** [comment]
We're not going to give bronze a blurb
