### ISSUE TITLE
Add Gold Sponsor WeWork

### ISSUE THREAD

**Issue by lukemelia** [goruco/goruco2018#42]

**Comment by jcn** [comment]
WeWork Technology is bridging the gap between physical and digital platforms, providing a delightful, seamless & powerful experience for members and employees. We build software that enables our members to connect with each other and the space around them like never before.

We develop tools that empower our community team to do what they do best - create a sense of community in every building. The Technology Team is a family of passionate, humble and collaborative individuals distributed in 5 countries with one goal in mind - to humanize through technology. We believe there's a macro shift toward a new way of work today-one focused on a movement towards meaning. WeWork Technology is proud to be is accelerating this movement.


![weworktechnology](https://user-images.githubusercontent.com/2909/40993095-a1e22b1e-68c6-11e8-8544-8a74118b6466.png)

**Comment by jcn** [comment]
@abelmartin The URL is https://technology.wework.com
