### ISSUE TITLE
Scholarship Sponsor logos should be smaller than logos of other sponsors with higher-tier sponsorships

### ISSUE THREAD

**Issue by lukemelia** [goruco/goruco2018#7]
They should be smaller than the Bronze level sponsors

**Comment by jcn** [comment]
@abelmartin Any word on this one?

**Comment by abelmartin** [comment]
Agreed.  I'm going to be free to do more web work tomorrow night.

**Comment by abelmartin** [comment]
Done.  Handled in the new design
